package ssm.test.cucumber.spring

import io.cucumber.spring.CucumberContextConfiguration
import org.springframework.cloud.function.context.test.FunctionalSpringBootTest

@CucumberContextConfiguration
@FunctionalSpringBootTest
class CucumberSpringConfiguration
